# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-26 10:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jlog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='termlog',
            name='timestamp',
            field=models.IntegerField(default=1466937880),
        ),
    ]
