# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-27 09:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jlog', '0002_auto_20160626_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='termlog',
            name='timestamp',
            field=models.IntegerField(default=1467021443),
        ),
    ]
