# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-28 08:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, default='', max_length=80, null=True),
        ),
    ]
